2021-08-24 14:44:31.017 - INFO - 16020 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.7, build f0df350
.
2021-08-24 14:44:31.019 - INFO - 16020 - azureml.train.automl.automlconfig._start_execution:217 - Submitting remote.
2021-08-24 14:52:07.659 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 14:52:07.688 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 14:52:07.712 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-24 14:52:08.004 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-24 14:52:09.817 - CRITICAL - 16020 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 852, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-08-24 14:52:09.818 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=1813.8[ms]
2021-08-24 14:52:09.820 - CRITICAL - 16020 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 804, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 852, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-08-24 14:52:09.820 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=2108.15[ms]
2021-08-24 14:52:09.821 - CRITICAL - 16020 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 640, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 804, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 852, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-08-24 14:52:09.822 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=2134.23[ms]
2021-08-24 14:52:09.823 - CRITICAL - 16020 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'AUC_weighted'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 708, in get_output
    curr_run, model_name = self._get_best_child_run(
  File "run.py", line 640, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 804, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 852, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-08-24 14:52:09.823 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=2164.76[ms]
2021-08-24 14:56:20.098 - INFO - 16020 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.7, build f0df350
.
2021-08-24 14:56:20.109 - INFO - 16020 - azureml.train.automl.automlconfig._start_execution:217 - Submitting remote.
2021-08-24 15:10:47.594 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:10:47.629 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:10:47.659 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-24 15:10:49.460 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=1801.33[ms]
2021-08-24 15:10:50.088 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=2458.86[ms]
2021-08-24 15:10:50.089 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-08-24 15:10:58.273 - CRITICAL - 16020 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-08-24 15:10:58.290 - WARNING - 16020 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.33.0'. Please install 'azureml-train-automl-runtime==1.33.0' (e.g. `pip install azureml-train-automl-runtime==1.33.0`) and then rerun the previous command.
2021-08-24 15:10:58.302 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=8212.98[ms]
2021-08-24 15:10:58.302 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=10707.81[ms]
2021-08-24 15:16:09.361 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:16:09.392 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:16:09.416 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-24 15:16:09.980 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=563.3[ms]
2021-08-24 15:16:10.240 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=848.26[ms]
2021-08-24 15:16:10.240 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-08-24 15:16:12.108 - CRITICAL - 16020 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-08-24 15:16:12.109 - WARNING - 16020 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.33.0'. Please install 'azureml-train-automl-runtime==1.33.0' (e.g. `pip install azureml-train-automl-runtime==1.33.0`) and then rerun the previous command.
2021-08-24 15:16:12.110 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=1870.2[ms]
2021-08-24 15:16:12.110 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=2749.53[ms]
2021-08-24 15:20:30.248 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:20:30.282 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:20:30.306 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-24 15:20:30.886 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=579.67[ms]
2021-08-24 15:20:31.267 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=985.48[ms]
2021-08-24 15:20:31.268 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-08-24 15:20:33.250 - CRITICAL - 16020 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-08-24 15:20:33.252 - WARNING - 16020 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.33.0'. Please install 'azureml-train-automl-runtime==1.33.0' (e.g. `pip install azureml-train-automl-runtime==1.33.0`) and then rerun the previous command.
2021-08-24 15:20:33.252 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=1983.05[ms]
2021-08-24 15:20:33.252 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=3003.61[ms]
2021-08-24 15:30:47.407 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:30:47.439 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:30:47.465 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-24 15:30:48.097 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=631.49[ms]
2021-08-24 15:30:48.342 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=903.4[ms]
2021-08-24 15:30:48.343 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-08-24 15:30:50.389 - CRITICAL - 16020 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-08-24 15:30:50.390 - WARNING - 16020 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.33.0'. Please install 'azureml-train-automl-runtime==1.33.0' (e.g. `pip install azureml-train-automl-runtime==1.33.0`) and then rerun the previous command.
2021-08-24 15:30:50.391 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=2047.66[ms]
2021-08-24 15:30:50.391 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=2984.39[ms]
2021-08-24 15:31:00.393 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:31:00.425 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-24 15:31:00.450 - INFO - 16020 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-24 15:31:01.519 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=1068.94[ms]
2021-08-24 15:31:02.535 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=2109.45[ms]
2021-08-24 15:31:02.535 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-08-24 15:31:05.716 - CRITICAL - 16020 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-08-24 15:31:05.717 - WARNING - 16020 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.33.0'. Please install 'azureml-train-automl-runtime==1.33.0' (e.g. `pip install azureml-train-automl-runtime==1.33.0`) and then rerun the previous command.
2021-08-24 15:31:05.718 - INFO - 16020 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=3182.71[ms]
2021-08-24 15:31:05.718 - INFO - 16020 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=5325.48[ms]
2021-08-29 20:28:27.002 - INFO - 14380 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.7, build f0df350
.
2021-08-29 20:28:27.014 - INFO - 14380 - azureml.train.automl.automlconfig._start_execution:217 - Submitting remote.
2021-08-29 20:57:00.917 - INFO - 14380 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-29 20:57:00.954 - INFO - 14380 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-08-29 20:57:00.982 - INFO - 14380 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-08-29 20:57:04.928 - INFO - 14380 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=3945.86[ms]
2021-08-29 20:57:06.900 - INFO - 14380 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=5946.41[ms]
2021-08-29 20:57:06.900 - INFO - 14380 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-08-29 20:57:17.707 - CRITICAL - 14380 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-08-29 20:57:17.729 - WARNING - 14380 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.33.0'. Please install 'azureml-train-automl-runtime==1.33.0' (e.g. `pip install azureml-train-automl-runtime==1.33.0`) and then rerun the previous command.
2021-08-29 20:57:17.732 - INFO - 14380 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=10832.2[ms]
2021-08-29 20:57:17.732 - INFO - 14380 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=16815.1[ms]
2021-09-02 12:12:51.470 - INFO - 23284 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.7, build f0df350
.
2021-09-02 12:12:51.471 - INFO - 23284 - azureml.train.automl.automlconfig._start_execution:217 - Submitting remote.
2021-09-02 12:29:38.436 - INFO - 23284 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-09-02 12:29:38.479 - INFO - 23284 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-09-02 12:29:38.511 - INFO - 23284 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-09-02 12:29:40.179 - INFO - 23284 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=1668.9[ms]
2021-09-02 12:29:40.926 - INFO - 23284 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=2447.0[ms]
2021-09-02 12:29:40.928 - INFO - 23284 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-09-02 12:29:45.674 - CRITICAL - 23284 - azureml.train.automl._model_download_utilities.log_traceback:227 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 180, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2021-09-02 12:29:45.699 - WARNING - 23284 - azureml.train.automl._model_download_utilities._download_automl_model:101 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.33.0'. Please install 'azureml-train-automl-runtime==1.33.0' (e.g. `pip install azureml-train-automl-runtime==1.33.0`) and then rerun the previous command.
2021-09-02 12:29:45.700 - INFO - 23284 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=4772.14[ms]
2021-09-02 12:29:45.700 - INFO - 23284 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=7263.5[ms]
